### ISSUE TITLE
Jinja2 inheritance ???

### ISSUE THREAD

**Issue by anselal** [app-generator/flask-material-dashboard#1]
Thank you for the great work combining creative tim's templates with Jinja2.
I have a question regarding how you handle those templates. Why do you use embedded `render_template` functions in the return statements like

https://github.com/app-generator/flask-material-dashboard/blob/3b9af39a238040d67c5f6219f607338c23e7b59c/app/views.py#L79

instead of using Jinja's inheritance function using the `extend` keyword in the templates?

**Comment by app-generator** [comment]
Hello @anselal, 

This UI kit will be migrated to a newer structure that uses inheritance and other improvements. 

Cheers!

**Comment by anselal** [comment]
Nice !!
